site_name: "Qiulin's Homepage"
site_url: "https://SaddySamoyed.github.io/"

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

nav:
  - Home: index.md
